:global:
  componentName: openshift4-nodes
  githubUrl: https://github.com/appuio/component-openshift4-nodes
  feature_goldenTests: true

docs/antora.yml:
  name: openshift4-nodes
  title: OpenShift 4 Nodes
